### ISSUE TITLE
 Backup Phrase recover

### ISSUE THREAD

**Issue by successhalf** [gitzhou/mnemonic-last-word#1]
I have a file that contains my seed phrase
There is no program to find the address / privatekey again?

**Comment by gitzhou** [comment]
> I have a file that contains my seed phrase
seed phrase? Do you mean the Mnemonic word or the optional passphrase?

> There is no program to find the address / privatekey again?
You need a tool to calculate address?

**Comment by successhalf** [comment]
> > I have a file that contains my seed phrase
> > There is no program to find the address / privatekey again?
> 
> Seed phrase? Do you mean the Mnemonic word or the optional passphrase?
> What do you want to recover? Or just need a tool to calculate address?

12 word phrase, lowercase, with spaces between each word, to recover  funds & transactions.
bulk i can't search by hand
I need a program to input 12 words phrase
output  address | Private key
1F5qrDynCi5hXwcmK8XQemiL5jZjczUVtT |L51jsPUMtSH4t9mcdMb56Hff8rH73x5uDapRUMaKR6TcL4RaQPPQ
https://prnt.sc/mrigrn

**Comment by gitzhou** [comment]
> > > I have a file that contains my seed phrase
> > > There is no program to find the address / privatekey again?
> > 
> > 
> > Seed phrase? Do you mean the Mnemonic word or the optional passphrase?
> > What do you want to recover? Or just need a tool to calculate address?
> 
> 12 word phrase, lowercase, with spaces between each word, to recover funds & transactions.
> bulk i can't search by hand
> I need a program to input 12 words phrase
> output address | Private key
> 1F5qrDynCi5hXwcmK8XQemiL5jZjczUVtT | L51jsPUMtSH4t9mcdMb56Hff8rH73x5uDapRUMaKR6TcL4RaQPPQ
> https://prnt.sc/mrigrn

That's not the purpose of this tool.
Batch automatically restore wallets from Mnemonic and derivation path is another program.
