### ISSUE TITLE
feedback to alternative solution 

### ISSUE THREAD

**Issue by merland** [gitzhou/mnemonic-last-word#2]
Hi, Nice work on the Windows app! 
I maintain a project that deals with the same problem: 
[http://seedpicker.net/calculator/last-word.html](http://seedpicker.net/calculator/last-word.html) (GH: merland/seedpicker) 
This tool can be run in offline mode on a secure computer. Would love some feedback from someone else interested in the same problem.

**Comment by gitzhou** [comment]
Aha, cool webpage 😄
